package fr.unistra.di.pmo.fsp.exception;

/**
 * Problems generated by application parameters.
 * @author virgile
 *
 */
public class ParameterException extends Exception
{
	private static final long serialVersionUID = 1155334773001284147L;

	/**
	 * Constructor.
	 * @param message problem origin
	 */
	public ParameterException(String message)
	{
		super(message);
	}
}
